seed_everything: true
trainer:
  accelerator: gpu
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 16-mixed
  max_epochs: 2000
  check_val_every_n_epoch: 20
  num_sanity_val_steps: -1
  log_every_n_steps: 100
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "../../checkpoints/vqgan/shapes3d"
        save_top_k: -1
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: "../../results/vqgan/"
      version: "shapes3d"
      name:

model:
  class_path: src.Open_MAGVIT2.models.video_lfqgan.VQModel
  init_args:
    ddconfig:
      double_z: False
      z_channels: 18
      resolution: 64
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,2,2,4]
      num_res_blocks: 4

    lossconfig:
      target: src.Open_MAGVIT2.modules.losses.video_vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_num_layers: 3
        disc_start: 0
        disc_weight: 0.8
        gen_loss_weight: 0.3
        lecam_loss_weight: 0.05
        codebook_weight: 0.1
        commit_weight: 0.25
        codebook_enlarge_ratio: 0
        codebook_enlarge_steps: 2000

    n_embed: 262144
    embed_dim: 18
    learning_rate: 1e-4
    sample_minimization_weight: 1.0
    batch_maximization_weight: 1.0
    scheduler_type: "None"
    use_ema: True
    image_pretrain_path: null
    sche_type: cos
    wpe: 0.01
    wp: 2
    wp0: 0.0
    max_iter:
    wp_iter:
    resume_lr:

data:
  class_path: main.DataModuleFromConfig
  init_args:
    batch_size: 2
    num_workers: 4
    train:
      target: src.Open_MAGVIT2.data.shape_video.ShapeVideoDataset
      params:
        config:
          size: 64
          mode: train
          sequence_length: 9
          dataset_size: 1000
          cache: true
          shape_scene_type: DIM_3
          shape_min_cubes: 2
          shape_max_cubes: 6
          shape_angle_min: 15
          shape_angle_max: 45
          shape_temporal_patterns: []
          shape_cache_dir: ../../data/shape_cache
    validation:
      target: src.Open_MAGVIT2.data.shape_video.ShapeVideoDataset
      params:
        config:
          size: 64
          mode: validation
          sequence_length: 9
          dataset_size: 100
          cache: true
          shape_scene_type: DIM_3
          shape_min_cubes: 2
          shape_max_cubes: 6
          shape_angle_min: 15
          shape_angle_max: 45
          shape_temporal_patterns: []
          shape_cache_dir: ../../data/shape_cache
    test:
      target: src.Open_MAGVIT2.data.shape_video.ShapeVideoDataset
      params:
        config:
          size: 64
          mode: test
          sequence_length: 9
          dataset_size: 100
          cache: true
          shape_scene_type: DIM_3
          shape_min_cubes: 2
          shape_max_cubes: 6
          shape_angle_min: 15
          shape_angle_max: 45
          shape_temporal_patterns: []
          shape_cache_dir: ../../data/shape_cache

ckpt_path: null
